global:
  imagePullSecrets:
    - space-applications-registry
    - dedl-registry
    - cs-gitlab-registry

stac:
  debug: true
  api:
    description: Searchable spatiotemporal catalog describing datasets hosted by the Destination Earth Data Lake
    landingPageId: dedl-stac
    title: DEDL STAC API

  initDb: true
  redisWait:
    enabled: false
  redisCluster: true
  redisTTL: 600
  tableValueTTL: 600
  rateLimit:
    collections: 2000
  backPressure:
    collections:
      reqPerSec: 1000
      incMs: 10

  image:
    registry: registry.gitlab.si.c-s.fr
    repository: dedl/argo-cd/eo-catalog
    tag: 0.2.0
    digest: ""
    pullPolicy: Always

  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: eo-catalog.dedl.csgroup.space
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls: true

  livenessProbe:
    enabled: false
    initialDelaySeconds: 30
  readinessProbe:
    enabled: false

  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
      ephemeral-storage: 50Mi

postgresql:
  enabled: false

externalDatabase:
  host: cnpg-postgis-ro
  hostWriter: cnpg-postgis-rw
  existingSecret: cnpg-postgis-credentials
  existingSecretPasswordKey: password
  existingSecretPostgresPasswordKey: postgres-password
  user: eo-catalog

redis:
  enabled: false
externalRedis:
  host: redis-cluster
  existingSecret: redis-cluster
  existingSecretPasswordKey: redis-password
