# Copyright 2025 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.cnpgstac.backup.barman.enabled }}
{{- if .Values.cnpgstac.backup.barman.barmanObjectStore }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ .Values.cnpgstac.backup.barman.barmanObjectStore.name }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: cnpgstac
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  configuration:
    destinationPath: {{ .Values.cnpgstac.backup.barman.barmanObjectStore.configuration.destinationPath }}
    endpointURL: {{ .Values.cnpgstac.backup.barman.barmanObjectStore.configuration.endpointURL }}
    s3Credentials:
      accessKeyId:
        key: {{ .Values.cnpgstac.backup.barman.barmanObjectStore.configuration.s3Credentials.accessKeyId}}
        name: {{ .Values.cnpgstac.backup.barman.barmanObjectStore.configuration.s3Credentials.secretName }}
      secretAccessKey:
        key: {{ .Values.cnpgstac.backup.barman.barmanObjectStore.configuration.s3Credentials.secretAccessKey }}
        name: {{ .Values.cnpgstac.backup.barman.barmanObjectStore.configuration.s3Credentials.secretName }}
    wal:
      compression: {{ .Values.cnpgstac.backup.barman.barmanObjectStore.configuration.wal.compression }}
    data:
      compression: {{ .Values.cnpgstac.backup.barman.barmanObjectStore.configuration.data.compression }}
  retentionPolicy: {{ .Values.cnpgstac.backup.barman.barmanObjectStore.retentionPolicy }}
{{- end }}
{{- end }}