{{- if and .Values.stac.enabled .Values.stac.horizontalPodAutoscaler.enabled -}}
  {{- if not .Values.stac.resources.requests }}
    {{- fail "stac.resources.requests is required if horizontalPodAutoscaler is enabled" -}}
  {{- end }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "eocatalog.stac" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "eocatalog.stac" . }}
  minReplicas: {{ .Values.stac.replicaCount }}
  maxReplicas: {{ .Values.stac.horizontalPodAutoscaler.maxReplicas }}
  metrics:
  {{- if .Values.stac.horizontalPodAutoscaler.cpuUtilization }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.stac.horizontalPodAutoscaler.cpuUtilization }}
  {{- end }}
  {{- if .Values.stac.horizontalPodAutoscaler.memUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.stac.horizontalPodAutoscaler.memUtilization }}
  {{- end }}
{{- end -}}
