{{- if and .Values.stac.enabled .Values.stac.ingress.enabled -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "eocatalog.stac" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: stac-api
  annotations:
    {{- if or .Values.stac.ingress.annotations .Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.stac.ingress.annotations .Values.commonAnnotations ) "context" . ) }}
    {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.stac.ingress.ingressClassName }}
  ingressClassName: {{ .Values.stac.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.stac.ingress.hostname }}
    - host: {{ .Values.stac.ingress.hostname }}
      http:
        paths:
          {{- if .Values.stac.ingress.extraPaths }}
          {{- toYaml .Values.stac.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.stac.ingress.path }}
            pathType: {{ .Values.stac.ingress.pathType }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "eocatalog.stac" .) "servicePort" "http" "context" $)  | nindent 14 }}
      {{- end }}
    {{- range .Values.stac.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "eocatalog.stac" $) "servicePort" "http" "context" $) | nindent 14 }}
    {{- end }}
    {{- if .Values.stac.ingress.extraRules }}
    {{- include "common.tplvalues.render" (dict "value" .Values.stac.ingress.extraRules "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .Values.stac.ingress.tls .Values.stac.ingress.extraTls }}
  tls:
    {{- if .Values.stac.ingress.tls }}
    - hosts:
        - {{ .Values.stac.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.stac.ingress.hostname }}
    {{- end }}
    {{- if .Values.stac.ingress.extraTls }}
    {{- include "common.tplvalues.render" (dict "value" .Values.stac.ingress.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}