ARG PYTHON_VERSION=3.11

FROM python:${PYTHON_VERSION}-slim

ENV CURL_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt

RUN apt update && apt install git postgresql-client -y

COPY runtimes/eoapi/stac /tmp/stac
RUN python -m pip install /tmp/stac[server,telemetry,redis] pypgstac[psycopg]
RUN rm -rf /tmp/stac

ENV MODULE_NAME eoapi.stac.app
ENV VARIABLE_NAME app

CMD [ "/bin/sh", "-c", "eocatalog-stac" ]
