ARG PYTHON_VERSION=3.11

FROM python:${PYTHON_VERSION}-slim

COPY runtimes/eoapi/vector /tmp/vector
RUN python -m pip install /tmp/vector
RUN rm -rf /tmp/vector

ENV MODULE_NAME eoapi.vector.app
ENV VARIABLE_NAME app
