ARG PYTHON_VERSION=3.11

FROM python:${PYTHON_VERSION}-slim

ENV CURL_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt

RUN python -m pip install psycopg[binary,pool]

COPY runtimes/eoapi/raster /tmp/raster
RUN python -m pip install /tmp/raster
RUN rm -rf /tmp/raster

ENV MODULE_NAME eoapi.raster.app
ENV VARIABLE_NAME app
