# Copyright 2025 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x
description: A CS Group STAC backend based on CloudNativePG PostGIS and PgSTAC.
home: https://github.com/csgroup-oss/eo-catalogue
icon: https://github.com/csgroup-oss/eo-catalog/raw/refs/heads/main/docs/static/eo-catalogue-logo-1080.webp
name: eo-cnpgstac
sources:
  - https://github.com/csgroup-oss/eo-catalogue
type: application
version: 1.0.0-alpha
appVersion: 0.9.8
